"""initial hardening schema

Revision ID: 4bb0e0e324a8
Revises:
Create Date: 2026-08-11 12:51:47.515955
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = "4bb0e0e324a8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_profiles",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_revision", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "preprocessing_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "scoring_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("general_tag_storage_threshold", sa.Float(), nullable=False),
        sa.Column("character_tag_storage_threshold", sa.Float(), nullable=False),
        sa.Column("general_tag_display_threshold", sa.Float(), nullable=False),
        sa.Column("character_tag_display_threshold", sa.Float(), nullable=False),
        sa.Column("auto_approve_threshold", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_profiles_model_name"),
        "analysis_profiles",
        ["model_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_profiles_model_revision"),
        "analysis_profiles",
        ["model_revision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_profiles_model_version"),
        "analysis_profiles",
        ["model_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_profiles_scoring_version"),
        "analysis_profiles",
        ["scoring_version"],
        unique=False,
    )
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "approval_mode",
            sa.Enum("AUTO", "MANUAL", name="approvalmode"),
            nullable=False,
        ),
        sa.Column("refresh_cron", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("refresh_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "download_base_dir", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("illustration_tagger_enabled", sa.Boolean(), nullable=False),
        sa.Column("illustration_auto_approve_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "active_analysis_profile_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("general_tag_display_threshold", sa.Float(), nullable=False),
        sa.Column("character_tag_display_threshold", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_runs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "RUNNING", "COMPLETED", "FAILED", name="refreshrunstatus"
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("new_items", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("downloads_triggered", sa.Integer(), nullable=False),
        sa.Column("downloads_failed", sa.Integer(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("claim_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_refresh_runs_active",
        "refresh_runs",
        ["status", "heartbeat_at", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_runs_claim_token"),
        "refresh_runs",
        ["claim_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_runs_heartbeat_at"),
        "refresh_runs",
        ["heartbeat_at"],
        unique=False,
    )
    op.create_table(
        "review_items",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("author_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("community_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("community_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("item_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "approval_status",
            sa.Enum("REJECTED", "APPROVED", "UNDER_REVIEW", name="approvalstatus"),
            nullable=False,
        ),
        sa.Column(
            "download_status",
            sa.Enum(
                "PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="downloadstatus"
            ),
            nullable=False,
        ),
        sa.Column("download_ready_at", sa.DateTime(), nullable=True),
        sa.Column("download_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("raw_data_json", sa.Text(), nullable=False),
        sa.Column("media_count", sa.Integer(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(), nullable=True),
        sa.Column("download_dir", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "download_claim_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("download_claimed_at", sa.DateTime(), nullable=True),
        sa.Column("download_heartbeat_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "source_item_id", name="uq_review_item_source_item"
        ),
    )
    op.create_index(
        op.f("ix_review_items_author_name"),
        "review_items",
        ["author_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_items_community_name"),
        "review_items",
        ["community_name"],
        unique=False,
    )
    op.create_index(
        "ix_review_items_created_cursor",
        "review_items",
        ["created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_review_items_download_claim",
        "review_items",
        ["approval_status", "download_status", "download_ready_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_items_download_claim_token"),
        "review_items",
        ["download_claim_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_items_download_heartbeat_at"),
        "review_items",
        ["download_heartbeat_at"],
        unique=False,
    )
    op.create_index(
        "ix_review_items_download_recovery",
        "review_items",
        ["download_status", "download_heartbeat_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_items_download_ready_at"),
        "review_items",
        ["download_ready_at"],
        unique=False,
    )
    op.create_index(
        "ix_review_items_list",
        "review_items",
        ["approval_status", "download_status", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_items_source"), "review_items", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_review_items_source_item_id"),
        "review_items",
        ["source_item_id"],
        unique=False,
    )
    op.create_table(
        "source_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum("WHITELIST", "BLACKLIST", name="listtype"),
            nullable=False,
        ),
        sa.Column(
            "target_type",
            sa.Enum("COMMUNITY", "AUTHOR", name="ruletargettype"),
            nullable=False,
        ),
        sa.Column("target_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "rule_type", "target_type", "target_value", name="uq_source_rule"
        ),
    )
    op.create_index(
        op.f("ix_source_rules_rule_type"), "source_rules", ["rule_type"], unique=False
    )
    op.create_index(
        op.f("ix_source_rules_source"), "source_rules", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_source_rules_target_type"),
        "source_rules",
        ["target_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_rules_target_value"),
        "source_rules",
        ["target_value"],
        unique=False,
    )
    op.create_table(
        "source_settings",
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("options_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("source"),
    )
    op.create_table(
        "media_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sort_index", sa.Integer(), nullable=False),
        sa.Column("media_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("download_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("preview_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("extension", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "download_strategy",
            sa.Enum("HTTP", "YT_DLP", name="downloadstrategy"),
            nullable=False,
        ),
        sa.Column(
            "approval_status",
            sa.Enum("REJECTED", "APPROVED", "UNDER_REVIEW", name="approvalstatus"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column(
            "illustration_label",
            sa.Enum("UNLABELED", "YES", "NO", "UNSURE", name="illustrationlabel"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["review_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "item_id", "sort_index", name="uq_media_attachment_item_sort"
        ),
    )
    op.create_index(
        op.f("ix_media_attachments_approval_status"),
        "media_attachments",
        ["approval_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_attachments_decided_at"),
        "media_attachments",
        ["decided_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_attachments_illustration_label"),
        "media_attachments",
        ["illustration_label"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_attachments_item_id"),
        "media_attachments",
        ["item_id"],
        unique=False,
    )
    op.create_table(
        "media_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=False),
        sa.Column(
            "analysis_profile_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_revision", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "preprocessing_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "scoring_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "FAILED", "SKIPPED", name="analysisstatus"),
            nullable=False,
        ),
        sa.Column("illustration_score", sa.Float(), nullable=True),
        sa.Column("general_tags_json", sa.Text(), nullable=False),
        sa.Column("character_tags_json", sa.Text(), nullable=False),
        sa.Column("ratings_json", sa.Text(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_profile_id"],
            ["analysis_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["media_attachments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attachment_id",
            "analysis_profile_id",
            name="uq_media_analysis_attachment_profile",
        ),
    )
    op.create_index(
        op.f("ix_media_analyses_analysis_profile_id"),
        "media_analyses",
        ["analysis_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_analyses_attachment_id"),
        "media_analyses",
        ["attachment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_analyses_illustration_score"),
        "media_analyses",
        ["illustration_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_analyses_model_name"),
        "media_analyses",
        ["model_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_analyses_model_revision"),
        "media_analyses",
        ["model_revision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_analyses_model_version"),
        "media_analyses",
        ["model_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_analyses_scoring_version"),
        "media_analyses",
        ["scoring_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_analyses_status"), "media_analyses", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_analyses_status"), table_name="media_analyses")
    op.drop_index(
        op.f("ix_media_analyses_scoring_version"), table_name="media_analyses"
    )
    op.drop_index(op.f("ix_media_analyses_model_version"), table_name="media_analyses")
    op.drop_index(op.f("ix_media_analyses_model_revision"), table_name="media_analyses")
    op.drop_index(op.f("ix_media_analyses_model_name"), table_name="media_analyses")
    op.drop_index(
        op.f("ix_media_analyses_illustration_score"), table_name="media_analyses"
    )
    op.drop_index(op.f("ix_media_analyses_attachment_id"), table_name="media_analyses")
    op.drop_index(
        op.f("ix_media_analyses_analysis_profile_id"), table_name="media_analyses"
    )
    op.drop_table("media_analyses")
    op.drop_index(op.f("ix_media_attachments_item_id"), table_name="media_attachments")
    op.drop_index(
        op.f("ix_media_attachments_illustration_label"), table_name="media_attachments"
    )
    op.drop_index(
        op.f("ix_media_attachments_decided_at"), table_name="media_attachments"
    )
    op.drop_index(
        op.f("ix_media_attachments_approval_status"), table_name="media_attachments"
    )
    op.drop_table("media_attachments")
    op.drop_table("source_settings")
    op.drop_index(op.f("ix_source_rules_target_value"), table_name="source_rules")
    op.drop_index(op.f("ix_source_rules_target_type"), table_name="source_rules")
    op.drop_index(op.f("ix_source_rules_source"), table_name="source_rules")
    op.drop_index(op.f("ix_source_rules_rule_type"), table_name="source_rules")
    op.drop_table("source_rules")
    op.drop_index(op.f("ix_review_items_source_item_id"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_source"), table_name="review_items")
    op.drop_index("ix_review_items_list", table_name="review_items")
    op.drop_index(op.f("ix_review_items_download_ready_at"), table_name="review_items")
    op.drop_index("ix_review_items_download_recovery", table_name="review_items")
    op.drop_index(
        op.f("ix_review_items_download_heartbeat_at"), table_name="review_items"
    )
    op.drop_index(
        op.f("ix_review_items_download_claim_token"), table_name="review_items"
    )
    op.drop_index("ix_review_items_download_claim", table_name="review_items")
    op.drop_index("ix_review_items_created_cursor", table_name="review_items")
    op.drop_index(op.f("ix_review_items_community_name"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_author_name"), table_name="review_items")
    op.drop_table("review_items")
    op.drop_index(op.f("ix_refresh_runs_heartbeat_at"), table_name="refresh_runs")
    op.drop_index(op.f("ix_refresh_runs_claim_token"), table_name="refresh_runs")
    op.drop_index("ix_refresh_runs_active", table_name="refresh_runs")
    op.drop_table("refresh_runs")
    op.drop_table("app_settings")
    op.drop_index(
        op.f("ix_analysis_profiles_scoring_version"), table_name="analysis_profiles"
    )
    op.drop_index(
        op.f("ix_analysis_profiles_model_version"), table_name="analysis_profiles"
    )
    op.drop_index(
        op.f("ix_analysis_profiles_model_revision"), table_name="analysis_profiles"
    )
    op.drop_index(
        op.f("ix_analysis_profiles_model_name"), table_name="analysis_profiles"
    )
    op.drop_table("analysis_profiles")
    # ### end Alembic commands ###
